### ISSUE TITLE
More knowls

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#118]
We should add more knowls to data entry fields.

**Comment by AndrewVSutherland** [comment]
I can do this (and then ask @poonen to help edit the content).  One UI comment/question, on the create seminar/institution pages we use <th> for captions (rather than <td>) which makes the knowl links show up in bold.  This has the advantage of making them more obvious but might become annoying on a page full of them, and differs from the styling on the LMFDB (e.g. https://www.lmfdb.org/Genus2Curve/Q/), although here we are talking about edit forms rather than search forms.  I think I might prefer them non-bold, with the exception of cases where they are column headings, as on https://mathseminars.org/edit/seminar/?shortname=vantage, for example, but I'd be curious what others think (we can wait until we have an example to look at on master to make a final decision).

**Comment by edgarcosta** [comment]
Agree.

Replacing th by td should fix the issue.

**Comment by AndrewVSutherland** [comment]
There are now knowls on the captions of all input boxes on create/edit pages except the user info page, where I don't think they are necessary.
