### ISSUE TITLE
First sentence at Register page

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#193]
I added a sentence at the Register page with links to the policies page and the privacy policy page.  I think it would be better if those links were edited to make them open in a new window/tab.  Also, someone should check that the links were done properly.  I'm not sure I understand the general recipe for citing other pages on the site, though sometimes I can guess from looking at other examples in the code.

**Comment by rbommel** [comment]
That looks good Bjorn. If you want to default to opening a new window/tab, you should add `target="_blank"` to the `<a>`-tag. Should there also be some check box where prospective users should confirm that they agree with the policies?

**Comment by AndrewVSutherland** [comment]
@rbommel I don't think this is necessary (this is not an end-user license agreement), and we don't want to go back and get acknowledgment from the users that have already registered (although we could add a one-time pop-up advising users to read the policy page).

I think it would be good to also add a link to the policy page on the create seminar page, since this is the first place where it is really relevant.

**Comment by AndrewVSutherland** [comment]
Hmm, after reading about this a bit more I think perhaps we should add a checkbox or at least a sentence that says that by clicking the register button they confirm they have read and agree to our policies.  We should probably also add a link to the policy page to our login page so that users who registered before the policy page was posted notice it (we could force a one-time acknowledgment by the user here, or give them the option to delete their account if they do not agree).

**Comment by edgarcosta** [comment]
Should we have a column with the last time they acknowledged our policies?
If that time is before the most recent update, what do we do?

**Comment by AndrewVSutherland** [comment]
@edgarcosta I like that idea; the more common approach  is to spam all your users with an email every time you update the policies, but we all know how annoying that is.  Ideally whenever we update the policies we would force every outstanding cookie to be treated as "expired" the next time the user visits the site so that they need to login again, and when they login note that the policies have been updated since they last visited.

It might make sense to distinguish creators (endorsed users) from regular users, since most of the policies only apply to people posting content.  But if we do that we would need to invalidate cookies for users when they get endorsed to force a new login (but maybe that can be combined with the cookie timeout -- put a timestamp in the cookie and compare it against the policy update timestamp, and then decide what action to take depending on whether the user is a creator or not.

We might also want to add a line to the policy page saying that we reserve the right to change the policies in the future.

**Comment by edgarcosta** [comment]
The only way I know how to invalidate session cookies is to change our secret key for the flask app.
Which means that everyone would get logged out.

**Comment by poonen** [comment]
I don't think we should require users to log in again every time we change the policies.  This would be annoying.  I think requiring them to check a box the first time they register is enough.  After that, the policy pages are always available to them.

**Comment by edgarcosta** [comment]
If it is one time only, then I would prefer to spam all the users after we add that button, instead of writing some code to handle the people that never saw the button.

**Comment by poonen** [comment]
Yes, after putting the checkbox on the register page, send a brief email to all registered users just saying that we have posted a policy page at http://...
(no need to mention the privacy policy separately, since the policy page now links to it)
and that going forward we expect users to respect the policies.

**Comment by poonen** [comment]
Here is a proposed email:
----
Dear mathseminars.org users,

This is a one-time email to announce that we have posted policies for use of the site at
https://mathseminars.org/policies
and that going forward we expect users to respect these.  Any questions or concerns can be directed to 
https://mathseminars.org/contact

Thank you,
The mathseminars.org administrators
----

**Comment by AndrewVSutherland** [comment]
I think this is fine as long as we add a line to the policy page saying we reserve the right to update the policies in the future.  Some sites also tell their users it is their responsibility to check for updates but most just spam everyone with an email every time they change a comma on their policy page.

One other thought: @edgarcosta rather than invalidating the cookie, could you just check a counter or timestamp to see if this cookie knows about the latest policy change and if not pop up a message mentioning that the policies have changed, like we do for cookie notifications?

**Comment by edgarcosta** [comment]
There are no timestamps on cookies. There are only expiration dates.

**Comment by AndrewVSutherland** [comment]
@edgarcosta You can store any string you want in a cookie as long as its short (and yes I know its not secure but for what we are talking about I don't think that matters).  This used to be very common back in the dark ages before everything moved server side (even things like the number of items in your shopping cart).

**Comment by AndrewVSutherland** [comment]
@edgarcosta You can go visit http://math.mit.edu/~drew/test.html for an example -- it updates a cookie each time you visit and keeps count of how many times it has seen you.

**Comment by edgarcosta** [comment]
Yes, we can do counters in cookies, but still doesn't address my main problem.
What we do with the current users?
Also, are we really going to annoy them everytime they switch browser or whatnot?

**Comment by rbommel** [comment]
Yes, I agree, it makes more sense to store it on the server and not in a cookie.

**Comment by roed314** [comment]
I think sending an email is a good idea, but let's hold off until we figure out what we're doing with the url so that we can include that info in the same message (especially since we'll need to be updating the policies to broaden beyond math).
