### ISSUE TITLE
Anywhere search

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#201]
I think it would be more useful if on the Search page, "Keywords" were replaced by "Anywhere" and the page really searched all displayable fields, including speaker, title, abstract, organizers, institution, etc.

I can't think of a common situation where one would want to see, say, talks whose abstract contains a name, while excluding talks whose speaker has that name.  In other words, I think it is rare that one would truly want to do only a keyword search.

MathSciNet already has searching "Anywhere" so people are already familiar with this.

**Comment by AndrewVSutherland** [comment]
I agree, and I also think we should be able to search by organizer name, external URL, and seminar identifier, see issue #23.  Having a separate input for these would be silly.  I'm going to close #23 and include that feature request in this issue.

**Comment by roed314** [comment]
We now search talks on title, abstract, speaker, speaker_affiliation, seminar_id, comments, speaker_homepage, paper_link; series on name, description, homepage, shortname, comments.  Seminar organizers is hard since they live in a different table and we don't have joins easily available.  Institutions is doable but annoying since they're in a list rather than a text field.

**Comment by roed314** [comment]
Good enough for now; we'll create follow up issues (e.g. #299).
