### ISSUE TITLE
Explaining why the link is not shown

### ISSUE THREAD

**Issue by davidfarmer** [roed314/seminars#209]
On this page
    https://mathseminars.org/talk/FRNTD/1/
it says "To see access link, you must be endorsed by another user."
That is a useful and informative message.

In this page
    https://mathseminars.org/talk/WisconsinNTS/1/
There is no indication of a link to watch online.  But I am pretty sure I sure a link was
visible to me some times but not others.  I cannot reproduce the problem.
I also think that one time when I saw the link, I clicked it and was asked for a
password, but had no way to determine the password.

I think the point I am making in this issue is:  if you are going to list seminars that
cannot be watched online, then those need to be clearly indicated (and make it easy
for me to never find out about them, because there is not much of a use case for
listing those unless you are restricting to my local area).  And if for some reason you
are not showing me the link to view, in that same place put a clear explanation of
why (such as "You must be logged in to see the access link".)

**Comment by AndrewVSutherland** [comment]
These are not software issues per se, they are issues with how the seminars are listed (we cannot prevent organizers/curators from saying that a seminar can be viewed online and then not give any information on how to do so).  In both cases the right thing to do is contact one of the listed contacts for the seminar, which you can find at:

https://mathseminars.org/seminar/FRNTD
https://mathseminars.org/seminar/WisconsinNTS

We should probably also list this contact information with the talk -- I will take care of this now.

In the latter case the contact is actually me!  I will email the seminar organizer and if they are not going to provide instructions on how to access the seminar (or if it is in fact private), I will remove the listing from mathseminars.org.  We actually inherited this listing from another site that decide to merge their listings with ours, which is how I wound up as the curator.

Regarding your point about filtering talks, the intention is to have a button you can click to see only talks that are listed online (or eventually, only near your physical location, or both).  We actually had this feature up on the live site but took it down because of issues in how many of the existing seminars are listed and the risk of confusion.  Once we have resolved these issues we will restore the ability to filter talks by venue (online, physical, or either).

**Comment by AndrewVSutherland** [comment]
@davidfarmer see the closed issue #84 for what happened with the "online" filtering of talks.

**Comment by AndrewVSutherland** [comment]
@davidfarmer You can see the updated talk page here:

https://master.mathseminars.org/talk/WisconsinNTS/1/

I'll push it to the live site shortly.

I also got in touch with the organizer Mark Shusterman and the livestream link is now listed, just click the "online" hyperlink to connect to the talk (in 4 hours).  This is already up on the live site.

**Comment by davidfarmer** [comment]
I guess I mistakenly assumed the form to submit a seminar had
a field for the link to the online broadcast, so there is no
issue of the organizers asserting whether there is a broadcast.

I saw that you were the contact person, but figured that was just
an artifact of the start-up process.

**Comment by AndrewVSutherland** [comment]
@davidfarmer There is a field for the livestream link, but we have to let organizers leave it blank (but still mark the seminar as online) because the link is often not posted until the day of the talk or even just 15 minutes before the talk starts.  The form tells organizers that in this case they should enter "see comments" in the livestream link field and explain how they make the link available in the comments, but this was not done in this case (it is now), see the next talk in the series by Noah Taylor, for example, where the link has yet to be posted:

https://mathseminars.org/talk/WisconsinNTS/2/

But you should really try posting a seminar you organize (or one you would like to curate on someone else's behalf) so that you can see it from the other side.  I just endorsed your account so you are free to create publicly visible content on mathseminars.org.
