### ISSUE TITLE
Pre-endorse users

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#27]
My guess is that one thing that is discouraging users from seeking endorsement is that they have to beg for it.  It would be great if we could "pre-endorse" a bunch of distinguished mathematicians so that they could get up and running quickly with no further involvement from us, so that the system would quickly be populated by high-quality seminars.  Also this would reduce the burden on the small number of current endorsed seminar organizers to endorse others.

I am not sure how best to implement this.

Maybe one way would be this (I think David or Edgar maybe suggested something along these lines?):  We store a file somewhere - each line of the file is an email address.  When a user registers with that email address and confirms it, that email address is automatically endorsed.  For this to work, the system should consult the file each time some newly registered user confirms an email address, to see if that user should be immediately endorsed.

An additional feature might be if, when I click "Endorse" on my Account page and the email address is not registered, the system added that email address to the file.

**Comment by rbommel** [comment]
It could be possible to pre-endorse users with e-mail addresses from whitelisted institutions, just like ArXiv does. This seems relatively safe...

**Comment by AndrewVSutherland** [comment]
@rbommel We discussed this but decided it wasn't a great idea.

**Comment by AndrewVSutherland** [comment]
Here is a proposal to change the way we manage endorsements that would also facilitate pre-endorsing:


When a user creates an account (or if they already have one they can do this on the account page), add a check box they can tick to indicate they are an organizer or curator, and explain that in this case they need to fill in their name/affiliation/webpage for verification.  If their email is already pre-endorsed (i.e. exists in a separate table of pre-endorsements), they would immediately be marked as endorsed and told they are good to go, but otherwise tell them we will let them know as soon as their account details have been verified.

On a separate page accessible only to admins, list users who have asked to be an organizer/curator but are not yet verified/endorsed where an admin can see their email/name/homepage details, sanity check them, and then tick a box to "endorse" them which would trigger an email telling them their account has been verified.

This would actually be less effort for us than what we are currently doing (monitoring the google group for endorsement requests as they trickle in, among other traffic), and would make the user experience smoother -- they don't have to ask anyone for anything, all they have to do is tick a box.

There are always going to be people who don't know anyone who is already endorsed, and this would give them an easy way to get endorsed.

**Comment by edgarcosta** [comment]
I will work on this after #34.

**Comment by AndrewVSutherland** [comment]
Also, as noted on #40, if a user's email is listed as the organizer of an existing seminar they should automatically be endorsed -- this could be discovered either when the create their account (in which case let them know about the seminar(s) they are listed as organizers on), or when someone else adds them as an organizer (anyone entering an organizer's email into a seminar they are editing is presumably happy to endorse them).  This would also make admin's lives easier (I am getting emails from organizers of conferences I am curating, and it would be great to be able to  just add them as an organizer and have them be good to go).

**Comment by edgarcosta** [comment]
#34 deals with the last part.
When a user confirms their email or logins we endorse them if they are organizers of some seminar.

**Comment by edgarcosta** [comment]
#85 once is live, we will be able to preendorse users

**Comment by tornaria** [comment]
Sorry to crash this (closed) issue.

What about also auto-pre-endorsing speakers?

**Comment by AndrewVSutherland** [comment]
Speakers can already be sent a link that will let them edit the details of their talk.  I don't think it makes sense to automatically pre-endorse them (although the organizers of the seminar can certainly do this if they wish).  The logic for doing this with organizers is that there is already content on our site that they might well have an interest in editing, but I expect most speakers won't have an immediate interest in editing any content other than their talk details.
