### ISSUE TITLE
Searching seminars by keyword

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#31]
If I search for seminars with the keyword "geometry" I get no hits, despite there being several seminars with "geometry" in the title.  Perhaps this is as intended, but I think it would be more intuitive if such a search did also search for the keyword in seminar titles.

**Comment by AndrewVSutherland** [comment]
I think the problem is that the seminar search only searches the description and comments, not the title.  This is also a problem with the talk search (if you type "Voronoi" in the keywords you will get no hits but if you put it in the title you will).  I think the keyword search should check every field that might conceivably contain a mathematical term.

**Comment by poonen** [comment]
I made this "high priority" because this is something that probably a lot of users, registered or not, are encountering.
