### ISSUE TITLE
Subject should be independent of topics

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#311]
Picking the subject should restrict your topic options on the multi-select, but we shouldn't depend on the topic to be select to deduce the subject.

If we don't want to go this path, then we need to require at least one topic to be selected at creation, but that is quite odd, for something like a colloquium series.

**Comment by poonen** [comment]
@edgarcosta: What page are you talking about?

**Comment by edgarcosta** [comment]
At the moment the subject of a talk/series is deduced from the topics field.
This has to lead to some hiccups discovered this morning when no topic was selected.

Thus we either allow users to specify a subject, perhaps set by default from your user settings, or we need to require at least one topic.

**Comment by AndrewVSutherland** [comment]
We could require either a non-empty list of topics or a subject (we don't need to allow both, each time they pick a topic they are also picking a subject).  I think its reasonable to insist that every series and talk should have at least one subject associated to it (otherwise they risk becoming invisible, as happened this morning).

**Comment by poonen** [comment]
Yes, I agree that each series and talk should be required to have at least one subject.

**Comment by roed314** [comment]
Currently there's no way for them to directly set the subject.  We had avoided adding such a mechanism since it was redundant with topics.  Should we just add a subject selector directly above the topic one?  I worry about the behavior there being confusing, especially since it's only relevant if no topics are selected.

Another possibility would be to have "Math - no topic" and "Physics - no topic" in the topic selector, which sets the subject but an empty topic (and are subsumed if there are any other topics in that discipline).  Then we require a "topic".  One benefit of this approach is that users are having to make an active choice to not assign a topic.  We could store this in the database as "math_" (to preserve the relation that subjects are derived from topics) then handle these topics slightly differently in display and filtering.

While we're working on this part of the code, what should the limit on number of subjects/topics for a single talk/series?  Maybe max of 2 subjects and max of 6 topics?

**Comment by poonen** [comment]
We agreed that users creating a series would on the initial create page be required to enter at least one subject.  

Then on the "Edit series" page, the series' current subjects would determine what topic options are available in the topics menu.  There would also be an option there to edit the subjects (this will be used only rarely), but then the user would be asked to reload the page so that the topic options would be updated.  Any time the series is saved, we require at least one subject to be set.

There is no need for "Math - no topic", etc.

**Comment by poonen** [comment]
What is the reason for imposing a maximum number of subjects and topics for a series?
Is it because of the implementation or because we think it is wrong to have more than that?
To me, 2 subjects seems too small an upper bound, and 6 topics also seems too small to me.

I would not impose a maximum on the number of subjects, at least not in the near future during which the number of subjects is small.  For topics, maybe 10 to 20?
I guess we want to discourage people from choosing them all?

**Comment by roed314** [comment]
There is no technical need to limit the number of subjects or topics.  The main motivation for doing so is to prevent people from trying to spam everyone by including lots of topics.  But maybe we should just wait to see if that actually becomes a problem before imposing a limit.

**Comment by poonen** [comment]
@roed314: OK, that sounds like a good plan.

**Comment by roed314** [comment]
Resolved by #326
