### ISSUE TITLE
Improve access control for livestreams

### ISSUE THREAD

**Issue by roed314** [roed314/seminars#327]
Currently we have an access dropdown with options "Open", "Logged-in users", "Endorsed users."  We ask people to put the zoom password in the comments field, but we have no way of checking if they've done so.  Some events require registration in advance.

This issue is for collecting ideas for improving the situation so that organizers don't worry about being Zoombombed and users can easily access seminars.

**Comment by roed314** [comment]
One idea: add a new field for a "password hint."  We could give examples like "the order of the symmetric group on 5 letters" or "the most common element in the universe."  If present, this field would be shown directly below the livestream link.   We could also have "registration required" be treated specially.

**Comment by AndrewVSutherland** [comment]
I like the idea of a password hint, and even suggestions for it, since this is pretty widely used -- it basically amounts to a captcha (which is something we could also offer).

There are different types of registration worth distinguishing:
- Meetings that require registering for the (possibly recurring) meeting on Zoom
- Series that require you to fill out a registration form on the external website
- Series that require you to join the mailing list

In the last two cases there are also different combinations of information emailed to registered users; (1) link and password (2) random link with no password (3) password to a public link.

Anything we can do to codify and standardize the most widely used options and encourage organizers to clearly specify the means of access will help everyone.

**Comment by roed314** [comment]
Access models (any of these can use a password hint):
* Link public and constant
* Link public, changes for each talk (comments should include when it will be announced)
* Link shown to logged in users
* Registration required (we require organizer to include the link or email, should specify deadline in comments)

We might later choose to add Captcha as an option.
We are removing the "link shown to endorsed users" model, and will email the organizers of the series currently using it.

We should also include stream link for last minute users when talk requires registration.

**Comment by AndrewVSutherland** [comment]
We need to address this soon.  I am getting a lot of emails from users who are confused because the comments don't make it clear what they are supposed to do (even in cases where the link is posted and no password or registration is required).

Just to refine the options proposed by @roed314 a bit, I would suggest the following properties would be associated to each series (most of them would not be editable per talk).  At a high level I think the four access models we should support are

- **open** (visible link shown with no password)
- **password hint** (visible link that requires a password and a hint for the password)
- **time window** (link published only 1-24 hours before the talk starts)
- **registration** (links/passwords sent to registered users, no link shown on our site)

Within these options there are several relevant parameters.

- **fixed** (same link used for every talk in the series, only relevant if registration is not required)
- **visibility** (everyone / logged-in users / captcha / ..., only relevant if registration is not required)
- **registration link** (URL a user clicks to register, email address or form)
- **registration cutoff** (number of hours a user must register in advance, after the cutoff we down't show a registration link for the talk and just say registration closed)
- **visible from** (number of hours before the talk links become visible; this would allow organizers to post links well in advance, possibly even when they create they talk)

In any case where the access options indicate that the organizer needs to post a link for each talk (all cases where registration is not required and fixed is false) we should email organizers 24 hours before the talk if the link has not been posted.

For the password hints I think we should just allow free text and not make suggestions, since these can be very domain specific.

I think most (possibly all) of these properties should be controlled at the series level, not the talk level.  In particular, they probably are not things a speaker with an edit link should see or be able to modify.  For talks without a fixed link, of course there needs to be a link for each talk, and we should probably allow the password hint to be customized at the talk level.
