### ISSUE TITLE
Make filtering on subject/topic pages more transparent

### ISSUE THREAD

**Issue by jamiesully** [roed314/seminars#392]
A user who arrives on a page like http://researchseminars.org/physics/hep-th might not realize that they aren't seeing all talks unless they look at the address bar. 

We could simply add something into browse.html like 

```
    {% if hide_filters | length > 0 %}
      <td>
        (<b>Some talks hidden: </b><a href="/">Browse all here</a>)
      </td>
    {% endif %}
```
with a result like:

![image](https://user-images.githubusercontent.com/25758486/81022625-ef1e6400-8e22-11ea-8194-98eec4bd4264.png)

**Comment by edgarcosta** [comment]
Looks good to me.

**Comment by poonen** [comment]
I agree that there should be some indication given.

Another way to do it might be to have a colored box (like those used when associating a topic to a series or talk) saying "x  Only algebraic geometry", where clicking the x inside the box makes this restrictor go away (i.e., returns you to the main page).  One advantage of this is that this would show <i>what</i> restriction is being imposed, though maybe it would already be obvious.  One other nitpick: "Browse all here" might be slightly misleading since there may be other filters still active; or would clicking this unset all the filters?

**Comment by roed314** [comment]
Another issue with the navigation to/from these pages: once you leave them there are no links back from the rest of the site.  In particular, if you click search then browse again, you'll be back to the browse page.

I don't have a good idea for how to fix this.

**Comment by roed314** [comment]
We've dropped these topic pages, so I'm closing this issue as no longer relevant.  If anyone has ideas on how to make such portals work, we're open to them.
