### ISSUE TITLE
Cancel changes on "Edit series" page should not redirect you

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#415]
Clicking "Cancel changes" on the "Edit series" page should leave you on the same page (but with changes cancelled, and with a message telling you that this has happened).

**Comment by AndrewVSutherland** [comment]
@poonen, I made this change on the Edit institution page (I was making other changes to it anyway) and was planning to do the same on the Edit series and Edit talk pages.  But before I do, can you look at the Edit institution page on master and let me know if it does what you want?  Try

    https://master.mathseminars.org/edit/institution/?shortname=MIT

I made "Cancel" into a button rather than a link, which I think is more consistent.  Currently the buttons just say "Save" and "Cancel", but perhaps they should say "Save all changes" and "Cancel all changes" like we do elsewhere? (although the situation seems clear on this page).

**Comment by poonen** [comment]
@AndrewVSutherland: Yes, that fixes what I was writing about, but 

1) I do think it is better to have "Cancel" look like a link instead of a button, or somehow otherwise to make it less prominent than the button, since it is the button that one is usually looking for.

2) I think that when the institution is being created for the first time, the "Cancel" should say "Cancel creation".  If editing, I suppose it could say "Cancel changes", since we don't want users to think we are deleting the institution.  The same applies to the Edit series and Edit talk pages, I think.

**Comment by AndrewVSutherland** [comment]
OK, I can make these changes to the Edit institution page, Edit series, Edit schedule, and Edit talk pages tomorrow.  I'll create a css class for the cancel button styled to look like a link (we can then  tweak it's appearance without having to choose between a button or a link, for the functionality you want, a button makes more sense, independent of what it looks like).

**Comment by poonen** [comment]
Maybe a button that had no solid color inside, but just a boundary, would be good for "Cancel creation" or "Cancel changes".

**Comment by AndrewVSutherland** [comment]
This has been done. we can restyle these further if need be, but the issue raised here has been addressed.
