### ISSUE TITLE
Biology topics

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#475]
Our current Biology DAG looks quite weird

<img width="320" alt="Screen Shot 2020-05-12 at 11 30 12" src="https://user-images.githubusercontent.com/322822/81713505-f4436a80-9443-11ea-8bf1-36603728e7e5.png">

We have `Cancer genetics` showing up at different levels.

**Comment by AndrewVSutherland** [comment]
I have a separate concern about using the Nature list of biology topics, or any list of topics of similar size.  Once we do this it will be hard to undo, and I don't think it is worth slowing down the entire site (and especially our front page) in order to provide this level of granularity.  I don't think we should use the AMS MSC codes as our topic trip for math for the same reason.   I think using either the bioarXiv topics or some reasonably small top-level subset of the Nature taxonomy (say something with less than 200 topics rather than close to 2000) would be better.

I don't necessarily object to allowing more topics to be specified when editing a series or talk, but I don't think we should be using them in our filtering mechanism on the front browse page.  The front page of our site is already too slow, even without the new topics.  The total load time for our front page has crept back up to 2.8s (on a 100+ megabit/s connection), we should be aiming to get the load time for the front page under 500ms.  Even if we start paging talks or switch to an infinite scroll, loading 2000 topics and all the details necessary to render the filter tree is going to make this hard to do.

**Comment by edgarcosta** [comment]
Here is another shorter list: https://en.wikipedia.org/wiki/Biology#Branches_and_career_options

Also agree, that the new infrastructure is a bit too heavy:
- 604k https://researchseminars.org/
- 2.8mb https://test.researchseminars.org/

**Comment by AndrewVSutherland** [comment]
Wikipedia is not a good source (it can be edited by anyone and researchers are not the target audience).  The cited references might be useful, but I'd be more inclined to go with something researchers are already using (e.g. bio-arXiv).  But we should really get some biologists to tell us what to do, subject to the constraint that the list of topics should ideally be less than 100.

It might be useful to know how many topics you get if you constrain the depth of the nature list (e.g. how many topics within distance 2 of the top?)

**Comment by edgarcosta** [comment]
I agree that Wikipedia is not curated, but might be a good start as it is
subdivided as a tree.

Bioxriv is also a good starting point, however, I do not think that it is
widely used by the community, so there might be bias there.


Overall we really need to get some input from various biologists on where
to look.

**Comment by poonen** [comment]
I agree that input from biologists is what is needed.  But we should expect the biology subtopics to occupy a large part of the topics graph, since it is a fact that biology is a much larger field than math or physics.

**Comment by roed314** [comment]
I'm going to close this for now, since we don't have a current intention to add subtopics to biology.  But if we start to get a lot of biology talks, we can revisit that decision.  I think the current best option is to increase the depth by one in the nature classification.
