### ISSUE TITLE
Right justify day in the Browse list

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#571]
In the talk list on the front page, right justify the day of the week to put it closer to the date.
Right now, for instance, there is way too much space between Fri and May 22.

**Comment by AndrewVSutherland** [comment]
We actually tried this once before and thought left-justified looked better (otherwise Fri looks very indented relative to Wed, here is a screen shot): 
![Screenshot from 2020-05-20 18-02-40](https://user-images.githubusercontent.com/11425002/82502191-973f5880-9ac4-11ea-9510-839a687acfa7.png)

But if you prefer this or just want to try it yourself, its an easy change, just modify line 672 of style.css (for the class table.ntda td.weekday) to use text-align: right; rather than text-align: left;

**Comment by poonen** [comment]
OK, I see what you mean.  Well, one benefit of the jagged left edge is that it sort of responds to the request for delimiters between dates!

Anyway, it looks bad both ways.  Even with right justification there is extra space because of differing month widths.

Right now on master I tried a third option, centering, which I think might be the best of the three, but I don't have a strong opinion, so feel free to change it back if you care.

**Comment by AndrewVSutherland** [comment]
I agree that centering looks better than either of the other two options, so I'm inclined to go with the change you made.
