### ISSUE TITLE
Asterisks to indicate required items

### ISSUE THREAD

**Issue by poonen** [roed314/seminars#83]
On the various forms, put a small red asterisk immediately to the right of the name of each required item.

**Comment by AndrewVSutherland** [comment]
@roed314 It would be easy for me to do this while I am turning the captions into knowl links.

**Comment by edgarcosta** [comment]
@AndrewVSutherland I would say go ahead. 
David is AFK at the moment.

**Comment by roed314** [comment]
Just got back, and I agree with Edgar: go ahead and do this.  Thanks!

**Comment by AndrewVSutherland** [comment]
on it.

**Comment by AndrewVSutherland** [comment]
If anyone has any quick feedback on https://master.mathseminars.org/manage/, that would be useful.  Questions are (1) do we like non-bold knowl titles (using td rather than th) and (2) should we put asterisk's on selectors where blank is not an option (e,g  the seminar/conference choice).   The argument for having it is that it alerts the user they are making a choice, the argument against is that they don't actually need to do anything, they can just take the default.  On (1) I think non-bold is better and I could go either way on (2).

**Comment by roed314** [comment]
I think it looks great.  I agree with the choice on non-bold knowls, and that we should include an asterisk on places like seminar/conference where we'd like them to make an active choice.  I think I might not include the asterisk on time zone (since there it's less likely that they'll need to change it) or on choices for talks that are carried over from the seminar.

**Comment by edgarcosta** [comment]
I'm on the non-asterisk camp on selectors where blank is not an option, but doesn't affect me very much.

**Comment by roed314** [comment]
I also don't have a strong opinion on the asterisk, so I think it's up to you Drew.

**Comment by AndrewVSutherland** [comment]
@roed314 I actually think the timezone selection is the most critical item when a new seminar is created -- if they don't pay attention to this bad things will happen.  We could distinguish between creation/edits and for some selectors only put an asterix on them during creation (but anything that can be made blank but is not allowed to be blank should always have an asterisk).

**Comment by poonen** [comment]
I'd favor interpreting an asterisk to mean "cannot be left blank", so I would include it even on items where a default will be selected.  Anyway, I don't feel strongly about this either.

**Comment by AndrewVSutherland** [comment]
I think I'm inclined to go with @poonen's suggestion, which has the virtue of uniformity and matches what I have done so far.

**Comment by edgarcosta** [comment]
Case closed then!
