### ISSUE TITLE
Livestream access link prominence

### ISSUE THREAD

**Issue by edgarcosta** [roed314/seminars#898]
At the moment, we place the live stream link at the bottom and with minimal emphasis if the talk is not about to start, e.g.:
![Screen Shot 2021-02-24 at 12 06 54](https://user-images.githubusercontent.com/322822/108998412-cb215d00-7698-11eb-8211-8028631ff9cb.png)

Should we style it more prominently even if the talk is not about to start now?

Furthermore, if the abstract is quite long, the link might be fully out of sight.
Should we also place a link on the right and below the speaker?
That is what we do when we are not inside the knowl (aka the popup)
![Screen Shot 2021-02-24 at 12 12 13](https://user-images.githubusercontent.com/322822/108998947-8944e680-7699-11eb-8c40-c06503f8fdb9.png)

CC: @chrisb13, @jamiesully

**Comment by AndrewVSutherland** [comment]
I'm not sure we should style it more prominently if the talk is about to start in general, since in most cases there is no rush to click on it unless the talk is about to start, and for talks more than a day or two in the future there often won't be a link posted yet.  The one possible exception is talks that require external registration, where we probably do want to draw people's attention to that.

I agree that moving it closer to the top of the knowl is a good idea.  I might suggest putting it immediately above the line that separates the speaker/title/topic tags from the abstract and series comment.  This would probably look reasonable and would just involving moving the div that is currently at the bottom of talk_knowl.html up a bit (note that there can be a lot more than just the livestream link that goes on the same line, e.g. a password hint or a view-only stream link, so it would be better just to keep that whole div intact).

**Comment by edgarcosta** [comment]
@AndrewVSutherland, I have just done what you suggested and it looks a bit weird. Check it out at https://master.researchseminars.org/

ps: topic tags were always below the abstract

**Comment by edgarcosta** [comment]
I did some slight improvements, aligning it on the left and having the "Lecture held in" sentence with a break at the end, all visible in https://master.researchseminars.org/
![Screen Shot 2021-02-24 at 13 48 52](https://user-images.githubusercontent.com/322822/109009905-09be1400-76a7-11eb-9b5f-564865370d4d.png)

**Comment by AndrewVSutherland** [comment]
@edgarcosta This looks reasonable to me, but if you are going to put it on the left make sure you still handle all the special cases (view-only link and live link, plus an optional password hint), but I would keep the live link on the left (so the mirror image of what we had when it was on the right).

I would tweak the margin-left/padding-left on the livestream box to make it flush with the left margin rather than slightly indented as it is now, and increase the margin-bottom by a few pixels so that the vertical space between the bottom of the livestream box and the top of the abstract matches the vertical spacing between the speaker/title/venue. But these are very minor changes.

**Comment by chrisb13** [comment]
Looks great :)

**Comment by roed314** [comment]
I think the change is good, and agree with Drew's comments on minor tweaks.
